
export const NEXT_APP_API_URL = process.env.NEXT_PUBLIC_APP_API_URL
export const REACT_APP_ASSET_URL = process.env.NEXT_PUBLIC_APP_API_URL

export const NEXT_PUBLIC_APP_API_URL = process.env.NEXT_PUBLIC_APP_API_URL
export const NEXT_PUBLIC_APP_ASSET_URL = process.env.NEXT_PUBLIC_APP_ASSET_URL
export const NEXT_PUBLIC_APP_CLIENT_SESSION_STORAGE_KEY = process.env.NEXT_PUBLIC_APP_CLIENT_SESSION_STORAGE_KEY

