// import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import '../styles/iconStyle.css';
import "@/styles/globals.css";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useState } from "react";
import { API_URL, FILTER, PROCESS, REACT_APP_API_URL } from "@/src/utlis/envConfig";
import { AppWrapper } from '../src/hooks/UserContext';
import { ToastContainer } from 'react-toastify';
import "@/styles/swiperStyle.css"

const apiKey = process.env.API_KEY;
const apiUrl = process.env.API_URL;
export default function App({ Component, pageProps }) {

    return (
        <>
            <Head>
                Welcome to Next.js  {process.env.myCustomEnvirement}
                <title>APEX</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
                <link rel="icon" href="/favicon.ico" />

                {/* Slick Slider Link */}
                <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
                <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />

            </Head>
            <AppWrapper>
                <Header />
                <Component {...pageProps}
                />
                <ToastContainer
                    position="top-right"
                    autoClose={5000}
                    hideProgressBar={false}
                    newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                />
                <Footer />
            </AppWrapper>
        </>
    );
}
